version: '3.5'
services:
  client:
    image: registry.chas.school/impostrious-dev-client:latest
    networks:
      - traefik
    deploy:
      labels:
        traefik.port: '80'
        traefik.enable: 'true'
        traefik.tags: 'traefik'
        traefik.backend: 'impostrious_dev_client'
        traefik.docker.network: 'traefik'
        traefik.frontend.rule: 'Host:impostrious-dev-client.chas.school'
        traefik.webservice.frontend.entryPoints: 'https'
        traefik.redirectorservice.frontend.entryPoints: 'http'
        traefik.redirectorservice.frontend.redirect.entryPoint: 'https'
    env_file:
      - .env

networks:
  traefik:
    external: true