version: "3.5"

services:
  api:
    image: registry.chas.school/impostrious-dev-api:latest
    working_dir: /app
    command: node build/server.js
    depends_on:
      - database
    env_file:
      - .env.dev
    networks:
      - traefik
      - backend
    deploy:
      labels:
        traefik.port: "5005"
        traefik.enable: "true"
        traefik.tags: "traefik"
        traefik.backend: "impostrious_dev_api"
        traefik.docker.network: "traefik"
        traefik.frontend.rule: "Host:impostrious-dev-api.chas.school"
        traefik.webservice.frontend.entryPoints: "https"
        traefik.redirectorservice.frontend.entryPoints: "http"
        traefik.redirectorservice.frontend.redirect.entryPoint: "https"
  database:
    image: "mongo"
    volumes:
      - ./mongo/001_create-users.js:/docker-entrypoint-initdb.d/001_create-users.js:ro
    env_file:
      - .env.dev
    networks:
      - backend
    deploy:
      labels:
        traefik.enable: "false"

volumes:
  database:

networks:
  traefik:
    external: true
  backend:
    external: false
