version: '3.5'

services:
  api:
    image: registry.chas.school/dev-impostrious-api:latest
    working_dir: /app
    command: node build/server.js
    environment:
      - POSTGRES_HOST=database
    depends_on:
      - database
    env_file:
      - .env.dev
    networks:
      - traefik
      - backend
    deploy:
      labels:
        traefik.port: '5005'
        traefik.backend: 'dev-impostrious'
        traefik.docker.network: 'traefik'
        traefik.frontend.rule: 'Host:impostrious-dev.chas.school'
  database:
    image: 'mongo'
    volumes:
      - 'database:/var/lib/postgresql/data'
    env_file:
      - .env.dev
    networks:
      - backend
    deploy:
      labels:
        traefik.enable: 'false'

volumes:
  database:

networks:
  traefik:
    external: true
  backend:
external: false