version: '3.5'

services:
  express_server:
    image: registry.chas.school/server:latest
    working_dir: /app
    command: node build/server.js
    depends_on:
      - database
    env_file:
      - .env.dev
    networks:
      - traefik
      - backend
    deploy:
      labels:
        traefik.port: '5005'
        traefik.backend: 'dev-impostrious'
        traefik.docker.network: 'traefik'
        traefik.frontend.rule: 'Host:impostrious-dev.chas.school'
  database:
    image: 'mongo'
    volumes:
      - ./server/deploy/mongo/001_create-users.js:/docker-entrypoint-initdb.d/001_create-users.js:ro
    env_file:
      - .env.dev
    networks:
      - backend
    deploy:
      labels:
        traefik.enable: 'false'

volumes:
  database:

networks:
  traefik:
    external: true
  backend:
    external: false